"""
Orchestrator — the pipeline that connects everything.

Flow:
1. Accept DeckSpec dict (generated by Hermes agent or loaded from file)
2. Fan-out: for slides needing images, call Grok Draw in parallel
3. Render each slide via HTML renderer
4. Render each slide via PPTX renderer
5. Assemble final outputs
"""
import json
import os
import re
import yaml
from pathlib import Path
from typing import Optional, Union, Any
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from copy import deepcopy
from pathlib import Path  # ensure Path available (already imported in some contexts)


# ─── Project paths ─────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).parent.parent
DESIGN_TOKENS_DIR = PROJECT_ROOT / "design-tokens" / "themes"
OUTPUT_DIR = PROJECT_ROOT / "output"


# ─── Grok Draw for image gen only ──────────────────────────────────────

def _generate_image(prompt: str) -> str:
    """Generate a single image via Grok Draw. Returns path."""
    from orchestrator.grok_draw import generate_image
    return generate_image(prompt)


def _generate_images(slides: list[dict]) -> None:
    """Generate images for all slides that need them, in parallel."""
    needs_image = [
        (i, s) for i, s in enumerate(slides)
        if s.get("content", {}).get("visual", {}).get("prompt")
    ]
    if not needs_image:
        return

    def gen(idx_slide):
        idx, s = idx_slide
        prompt = s["content"]["visual"]["prompt"]
        try:
            path = _generate_image(prompt)
            s["content"]["visual"]["generated_path"] = path
            print(f"  🖼️  Slide {s.get('order', '?')} image: {Path(path).name}")
        except Exception as e:
            print(f"  ⚠️  Slide {s.get('order', '?')} image failed: {e}")

    with ThreadPoolExecutor(max_workers=3) as pool:
        for item in needs_image:
            gen(item)


def _generate_background_image(prompt: str, theme_colors: dict = None) -> str:
    """Generate a full-bleed background image via Grok Draw. Returns path."""
    from orchestrator.grok_draw import generate_background
    return generate_background(prompt, theme_colors)


# ─── Main Pipeline ─────────────────────────────────────────────────────

def generate(
    spec: Union[dict, str, Path],
    output_name: str = None,
    build_steps: bool = True,
    standalone: bool = True,
    css_path: Optional[str] = None,
    js_path: Optional[str] = None,
    verify: bool = True,
) -> dict:
    """Generate slides from a DeckSpec.

    Clean public API intended for external callers (e.g. presentation-builder / Hermes layer).

    Accepts:
      - dict conforming to DeckSpec
      - str or Path to a .json DeckSpec file (will be loaded)

    The function:
      - Validates against the Pydantic schema (best effort)
      - Deep-copies the input so callers are not mutated
      - Generates images for both `content.visual.prompt` and background_prompt
      - Copies all assets (visuals + backgrounds) into a self-contained _images/ folder
      - Renders HTML + PPTX
      - Returns artifact paths

    Full pipeline: (DeckSpec | path) -> rendered deck + assets.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # --- Clean external API: accept path or dict + validation + no mutation ---
    if isinstance(spec, (str, Path)):
        with open(spec, encoding="utf-8") as f:
            spec = json.load(f)

    # Best-effort schema validation (non-fatal to stay flexible during development)
    try:
        from deckspec.schema import DeckSpec
        DeckSpec.model_validate(spec)
    except Exception as ve:
        print(f"⚠️  DeckSpec validation warning: {ve}")

    spec = deepcopy(spec)  # protect the caller's data structure

    if not output_name:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_name = f"deck_{ts}"

    theme = spec.get("global_design", {}).get("theme_id", "clinic-warm")
    slides = spec.get("slides", [])
    assert slides, "No slides in spec"

    print(f"📋 Deck: {spec.get('title', 'Untitled')} ({len(slides)} slides)")
    print(f"🎨 Theme: {theme}")

    # Load design tokens early (required for theme-aware background generation)
    token_path = DESIGN_TOKENS_DIR / f"{theme}.yaml"
    if not token_path.exists():
        raise FileNotFoundError(f"Theme not found: {token_path}")
    with open(token_path) as f:
        tokens = yaml.safe_load(f)

    # Step 1: Generate images (visuals + backgrounds)
    # Visuals (content images)
    image_slides = [s for s in slides if s.get("content", {}).get("visual", {}).get("prompt")]
    if image_slides:
        print(f"🎨 Generating {len(image_slides)} images via Grok Draw...")
        _generate_images(slides)

    # Backgrounds (full-bleed) - new support
    bg_needs = []
    for i, s in enumerate(slides):
        bp = s.get("background_prompt")
        bi = s.get("background_image")
        if bp and not (isinstance(bi, (str, Path)) and Path(str(bi)).exists()):
            bg_needs.append((i, s))
    if bg_needs:
        print(f"🎨 Generating {len(bg_needs)} background images via Grok Draw...")
        def gen_bg(idx_s):
            idx, s = idx_s
            prompt = s.get("background_prompt")
            colors = (tokens or {}).get("colors", {})
            try:
                path = _generate_background_image(prompt, colors)
                s["background_image"] = path
                print(f"  🖼️  Slide {s.get('order', '?')} background: {Path(path).name}")
            except Exception as e:
                print(f"  ⚠️  Slide {s.get('order', '?')} background failed: {e}")
        with ThreadPoolExecutor(max_workers=3) as pool:
            for item in bg_needs:
                gen_bg(item)

    # Copy all image assets (visuals + backgrounds) to output/<name>_images for self-contained delivery
    images_dir = OUTPUT_DIR / f"{output_name}_images"
    images_dir.mkdir(exist_ok=True)
    import shutil
    for s in slides:
        order = s.get("order", 0)
        # Visual / content image
        vis = s.get("content", {}).get("visual", {}) or {}
        gen_path = vis.get("generated_path")
        if gen_path and os.path.exists(str(gen_path)):
            ext = os.path.splitext(str(gen_path))[1] or ".jpg"
            img_name = f"slide_{order:02d}{ext}"
            dest = images_dir / img_name
            if os.path.abspath(str(gen_path)) != os.path.abspath(str(dest)):
                shutil.copy2(str(gen_path), str(dest))
                vis["generated_path"] = str(dest)
        # Background image (full-bleed) - now handled uniformly
        bg_path = s.get("background_image")
        if bg_path and os.path.exists(str(bg_path)):
            ext = os.path.splitext(str(bg_path))[1] or ".jpg"
            bg_name = f"slide_{order:02d}_bg{ext}"
            dest = images_dir / bg_name
            if os.path.abspath(str(bg_path)) != os.path.abspath(str(dest)):
                shutil.copy2(str(bg_path), str(dest))
                s["background_image"] = str(dest)  # point to packaged copy for relpaths

    # Step 3: Render HTML
    print(f"🌐 Rendering HTML...")
    from renderers.html.renderer import render_deck as html_render
    # Read build_steps from spec global_design, CLI override wins
    # build_steps / standalone etc: explicit args win over spec.global_design
    g = spec.get("global_design", {}) or {}
    deck_build_steps = build_steps if build_steps is not None else g.get("build_steps", True)
    use_standalone = standalone if standalone is not None else g.get("standalone", True)
    use_css_path = css_path if css_path is not None else g.get("css_path")
    use_js_path = js_path if js_path is not None else g.get("js_path")
    html_title = spec.get("title", "Presentation")
    html_content = html_render(
        slides, tokens,
        output_dir=str(OUTPUT_DIR),
        build_steps=deck_build_steps,
        standalone=use_standalone,
        css_path=use_css_path,
        js_path=use_js_path,
        title=html_title,
    )
    html_path = OUTPUT_DIR / f"{output_name}.html"
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"  ✅ HTML: {html_path}")

    # For external mode with default asset paths, copy slidecraft.css + slider.js
    # alongside the .html so relative refs resolve for file:// / static hosting.
    if not use_standalone and (use_css_path is None and use_js_path is None):
        out_dir = html_path.parent
        for asset_fname, pkg_rel in [
            ("slidecraft.css", "renderers/html/slidecraft.css"),
            ("slider.js", "renderers/html/slider.js"),
        ]:
            target_path = out_dir / asset_fname
            src = PROJECT_ROOT / pkg_rel
            if src.exists() and not target_path.exists():
                shutil.copy2(str(src), str(target_path))
                print(f"  📎 Copied asset for external mode: {asset_fname}")

    # Step 4: Render PPTX
    print(f"📊 Rendering PPTX...")
    from renderers.pptx.renderer import render_deck as pptx_render
    pptx_path = str(OUTPUT_DIR / f"{output_name}.pptx")
    pptx_result = pptx_render(slides, tokens, pptx_path)
    print(f"  ✅ PPTX: {pptx_result}")

    # Save spec
    spec_path = OUTPUT_DIR / f"{output_name}.spec.json"
    with open(spec_path, "w", encoding="utf-8") as f:
        json.dump(spec, f, ensure_ascii=False, indent=2)

    # Step 5: Contrast verification (post-render QA gate)
    if verify:
        print(f"🎨 Running contrast verification...")
        try:
            import importlib.util
            spec_mod = importlib.util.spec_from_file_location(
                "verify_contrast",
                str(PROJECT_ROOT / "scripts" / "verify-contrast.py")
            )
            if spec_mod:
                vc_mod = importlib.util.module_from_spec(spec_mod)
                spec_mod.loader.exec_module(vc_mod)
                vresult = vc_mod.verify_deck(str(html_path))
                if vresult["pass"]:
                    print(f"  ✅ Contrast: {vresult['total']}/{vresult['total']} slides pass")
                else:
                    failed = sum(1 for s in vresult["slides"] if not s["pass"])
                    print(f"  ⚠️  Contrast: {failed}/{vresult['total']} slides FAIL")
                    for s in vresult["slides"]:
                        if not s["pass"]:
                            print(f"    ❌ Slide {s['slide']} [{s['layout']}]")
                vc_mod.print_report(vresult)
            else:
                print(f"  ⚠️  verify-contrast.py not found — skipping QA")
        except Exception as ve:
            print(f"  ⚠️  Contrast verification error: {ve}")
    else:
        print(f"  ⏭️  Contrast verification skipped (verify=False)")

    print(f"\n✨ Done! Output: {OUTPUT_DIR / output_name}.*")
    return {
        "html": str(html_path),
        "pptx": pptx_result,
        "spec": str(spec_path),
        "slides": len(slides),
        "title": spec.get("title", ""),
    }


def generate_from_deckspec_file(
    spec_path: Union[str, Path],
    output_name: str = None,
    **kwargs
) -> dict:
    """Convenience wrapper: load a DeckSpec JSON file and call generate().

    This makes the new clean API (path support + validation + no-mutation)
    easily usable from CLI and external tools (e.g. presentation-builder).

    All other kwargs (build_steps, standalone, etc.) are forwarded to generate().
    """
    if isinstance(spec_path, (str, Path)):
        with open(spec_path, encoding="utf-8") as f:
            spec = json.load(f)
    else:
        spec = spec_path
    return generate(spec, output_name=output_name, **kwargs)
