"""
Orchestrator — the pipeline that connects everything.

Flow:
1. Accept DeckSpec dict (generated by Hermes agent or loaded from file)
2. Fan-out: for slides needing images, call Grok Draw in parallel
3. Render each slide via HTML renderer
4. Render each slide via PPTX renderer
5. Assemble final outputs
"""
import json
import os
import re
import yaml
from pathlib import Path
from typing import Optional
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime


# ─── Project paths ─────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).parent.parent
DESIGN_TOKENS_DIR = PROJECT_ROOT / "design-tokens" / "themes"
OUTPUT_DIR = PROJECT_ROOT / "output"


# ─── Grok Draw for image gen only ──────────────────────────────────────

def _generate_image(prompt: str) -> str:
    """Generate a single image via Grok Draw. Returns path."""
    from orchestrator.grok_draw import generate_image
    return generate_image(prompt)


def _generate_images(slides: list[dict]) -> None:
    """Generate images for all slides that need them, in parallel."""
    needs_image = [
        (i, s) for i, s in enumerate(slides)
        if s.get("content", {}).get("visual", {}).get("prompt")
    ]
    if not needs_image:
        return

    def gen(idx_slide):
        idx, s = idx_slide
        prompt = s["content"]["visual"]["prompt"]
        try:
            path = _generate_image(prompt)
            s["content"]["visual"]["generated_path"] = path
            print(f"  🖼️  Slide {s.get('order', '?')} image: {Path(path).name}")
        except Exception as e:
            print(f"  ⚠️  Slide {s.get('order', '?')} image failed: {e}")

    with ThreadPoolExecutor(max_workers=3) as pool:
        for item in needs_image:
            gen(item)


# ─── Main Pipeline ─────────────────────────────────────────────────────

def generate(
    spec: dict,
    output_name: str = None,
    build_steps: bool = True,
    standalone: bool = True,
    css_path: Optional[str] = None,
    js_path: Optional[str] = None,
) -> dict:
    """Generate slides from a DeckSpec dict.

    Full pipeline: spec -> deck.

    Args:
        spec: DeckSpec dict (with 'slides', 'global_design', 'title')
        output_name: Optional output filename prefix

    Returns:
        Dict with paths to generated files
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    if not output_name:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_name = f"deck_{ts}"

    theme = spec.get("global_design", {}).get("theme_id", "clinic-warm")
    slides = spec.get("slides", [])
    assert slides, "No slides in spec"

    print(f"📋 Deck: {spec.get('title', 'Untitled')} ({len(slides)} slides)")
    print(f"🎨 Theme: {theme}")

    # Step 1: Generate images (in parallel)
    image_slides = [s for s in slides if s.get("content", {}).get("visual", {}).get("prompt")]
    if image_slides:
        print(f"🎨 Generating {len(image_slides)} images via Grok Draw...")
        _generate_images(slides)

    # Copy images to output dir for local file:// viewing
    images_dir = OUTPUT_DIR / f"{output_name}_images"
    images_dir.mkdir(exist_ok=True)
    import shutil
    for s in slides:
        vis = s.get("content", {}).get("visual", {})
        gen_path = vis.get("generated_path")
        if gen_path and os.path.exists(gen_path):
            ext = os.path.splitext(gen_path)[1] or ".jpg"
            img_name = f"slide_{s.get('order', 0):02d}{ext}"
            dest = images_dir / img_name
            if os.path.abspath(gen_path) != os.path.abspath(str(dest)):
                shutil.copy2(gen_path, str(dest))
                vis["generated_path"] = str(dest)  # Relative-safe absolute path

    # Step 2: Load design tokens
    token_path = DESIGN_TOKENS_DIR / f"{theme}.yaml"
    if not token_path.exists():
        raise FileNotFoundError(f"Theme not found: {token_path}")
    with open(token_path) as f:
        tokens = yaml.safe_load(f)

    # Step 3: Render HTML
    print(f"🌐 Rendering HTML...")
    from renderers.html.renderer import render_deck as html_render
    # Read build_steps from spec global_design, CLI override wins
    # build_steps / standalone etc: explicit args win over spec.global_design
    g = spec.get("global_design", {}) or {}
    deck_build_steps = build_steps if build_steps is not None else g.get("build_steps", True)
    use_standalone = standalone if standalone is not None else g.get("standalone", True)
    use_css_path = css_path if css_path is not None else g.get("css_path")
    use_js_path = js_path if js_path is not None else g.get("js_path")
    html_title = spec.get("title", "Presentation")
    html_content = html_render(
        slides, tokens,
        output_dir=str(OUTPUT_DIR),
        build_steps=deck_build_steps,
        standalone=use_standalone,
        css_path=use_css_path,
        js_path=use_js_path,
        title=html_title,
    )
    html_path = OUTPUT_DIR / f"{output_name}.html"
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)
    print(f"  ✅ HTML: {html_path}")

    # For external mode with default asset paths, copy slidecraft.css + slider.js
    # alongside the .html so relative refs resolve for file:// / static hosting.
    if not use_standalone and (use_css_path is None and use_js_path is None):
        out_dir = html_path.parent
        for asset_fname, pkg_rel in [
            ("slidecraft.css", "renderers/html/slidecraft.css"),
            ("slider.js", "renderers/html/slider.js"),
        ]:
            target_path = out_dir / asset_fname
            src = PROJECT_ROOT / pkg_rel
            if src.exists() and not target_path.exists():
                shutil.copy2(str(src), str(target_path))
                print(f"  📎 Copied asset for external mode: {asset_fname}")

    # Step 4: Render PPTX
    print(f"📊 Rendering PPTX...")
    from renderers.pptx.renderer import render_deck as pptx_render
    pptx_path = str(OUTPUT_DIR / f"{output_name}.pptx")
    pptx_result = pptx_render(slides, tokens, pptx_path)
    print(f"  ✅ PPTX: {pptx_result}")

    # Save spec
    spec_path = OUTPUT_DIR / f"{output_name}.spec.json"
    with open(spec_path, "w", encoding="utf-8") as f:
        json.dump(spec, f, ensure_ascii=False, indent=2)

    print(f"\n✨ Done! Output: {OUTPUT_DIR / output_name}.*")
    return {
        "html": str(html_path),
        "pptx": pptx_result,
        "spec": str(spec_path),
        "slides": len(slides),
        "title": spec.get("title", ""),
    }
